#!/bin/bash

PASS=$(cat ../../.pw)

for host in $(awk '/sbm/ {print $2}' /etc/hosts); do
	echo "**********  $host  **********"
	sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S /usr/bin/flightCheck|grep ERROR" 2>/dev/null 
done

