#!/bin/bash
PASS=$(cat .pw)
for host in $(awk '/sbm/ {print $2}' /etc/hosts); do 
	echo "issuing chmod 700 /home/continuum/maxmtu.sh on $host"
	sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host chmod 700 /home/continuum/maxmtu.sh 2>/dev/null
done

