#!/bin/bash

PASS=$(cat .pw)

for host in $(awk '/csbm/ {print $2}' /etc/hosts); do
	echo "*** $host ***"
	#sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S df -h /storage* | sort -rnk +5" 2>/dev/null
	sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S df -h /storage* | sort -rnk +5 | awk '{ if (\$5 > 80) print }'" 2>/dev/null
done
