#!/bin/bash

PASS=$(cat .pw)

get_deleted() {
	host=$1
	sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S find /storage* -name *.deleted -mtime +90 -exec du -sk {} \;" 2>/dev/null
}

get_sums() {
	for host in $(awk '/sbm/ {print $2}' /etc/hosts); do
		n=$(get_deleted $host  | awk '{total += $1 * 1024} END {printf "%.f\n", total}')
		data=$(numfmt --to=iec-i --suffix=B --padding=7 $n)
		echo "$host -> $data"
	done
}

get_sums | egrep -v "GiB|0B" | sed 's/TiB//g' | awk '{print $1" "$2" "$3} {total += $3} END {printf "%.f TiB\n", total}'
