#!/bin/bash

PASS=$(cat .pw)
DSID=$1

if [[ -z $1 ]]; then
	echo "usage: $0 <diskSafeID>"
	exit -1
fi

for host in $(awk '/csbm/ {print $2}' /etc/hosts); do
	data=$(sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S find /storage* -name $DSID -exec du -sh {} \;" 2>/dev/null) 
	if [[ ! -z $data ]]; then
		echo "$host $data"
	fi
done
