#!/bin/bash

PASS=$(cat .pw) 
for host in $(awk '/sbm/ {print $2}' /etc/hosts); do  
	sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S /home/continuum/xfs_frag" 2>/dev/null | grep WARN
done
