#!/bin/bash

PASS=$(cat .pw)

getDeletedAgents() {
	for host in $(awk '/sbm/ {print $2}' /etc/hosts); do  
		sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S find /storage*/replication -exec du -sh {} + | sed 's/^/$host,/'" 2>/dev/null
	done
}

getDeletedAgents  > all_agents.txt
sed 's/	/,/g' all_agents.txt > all_agents.csv
cat all_agents.csv
