#!/bin/bash

PASS=$(cat .pw)

getDeletedAgents() {
	for host in $(awk '/sbm/ {print $2}' /etc/hosts); do  
		echo "**********   $host   *************"
		sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S find /storage* -name *.deleted -mtime +76 -exec du -sh {} \;" 2>/dev/null
	done
}

getDeletedAgents > old_agents_deleted.txt
cat old_agents_deleted.txt
./parse_old_agents.pl
