#!/bin/bash

PASS=$(cat .pw)

getDeletedAgents() {
	for host in $(awk '/sbm/ {print $2}' /etc/hosts); do  
		sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S find /storage* -name *.deleted -mtime +73 -exec du -sh {} + | sed 's/^/$host,/'" 2>/dev/null
	done
}

getDeletedAgents  > old_agents_deleted.txt
sed 's/	/,/g' old_agents_deleted.txt > old_agents.csv
cat old_agents.csv
./parse_old_agents.pl
