#!/bin/bash

PASS=$(cat .pw)

for host in $(awk '/sbm/ {print $2}' /etc/hosts); do  
	echo "**********   $host   *************"
	sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S find /storage* -name *.deleted -mtime +76 -exec du -sh {} \;" 2>/dev/null
done
