#!/usr/bin/env python

import urllib2
import sys

def getFailoverStatus(id):
    url = "http://10.80.65.31:57988/r1rmGA/fail/"+id
    print url
    response = urllib2.urlopen(url)
    content = response.read()
    return content

def usage():
    print "  usage: " + sys.argv[0] + " <Failover ID>"
    print "example: " + sys.argv[0] + " d9615005-a843-4776-a130-e09f3c193711"

def main():
    if len(sys.argv) != 2:
        usage()
        sys.exit(2)

    id = sys.argv[1]
    fo = getFailoverStatus(id)

    print fo

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit()
        
