#!/usr/bin/env python

import urllib2
import sys

def getLiveConfig(csbm):
    url = "http://10.80.65.31:57988/r1rmGA/csbm/"+csbm+"/liveConfig"
    print url
    response = urllib2.urlopen(url)
    content = response.read()
    return content

def usage():
    print "  usage: " + sys.argv[0] + " <CSBM GUID>"
    print "example: " + sys.argv[0] + " f8981d09-bb9a-4dad-8947-75ea5bd3a4dc"

def main():
    if len(sys.argv) != 2:
        usage()
        sys.exit(2)

    csbm = sys.argv[1]
    lc = getLiveConfig(csbm)

    print lc

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit()
        
