#!/usr/bin/env python

import urllib2
import sys

def getTaskInfo(id):
    url = "http://10.80.65.31:57988/r1rmGA/task/"+id+"/info"
    print url
    response = urllib2.urlopen(url, timeout=40)
    content = response.read()
    return content

def usage():
    print "  usage: " + sys.argv[0] + " <Task ID>"
    print "example: " + sys.argv[0] + " f0f20b83-d080-48d0-bdd1-e9ab7e5591c8"

def main():
    if len(sys.argv) != 2:
        usage()
        sys.exit(2)

    id = sys.argv[1]
    t = getTaskInfo(id)

    print t

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit()
        
