#!/bin/bash

PCKG=$1
PASS=$(cat .pw)

if [[ -z $1 ]]; then
	echo "usage: $0 <package>"
	exit -1
fi

for host in $(awk '/csbm/ {print $2}' /etc/hosts); do
	data=$(sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S apt install $PCKG" 2>/dev/null) 
	if [[ ! -z $data ]]; then
		echo "$host $data"
	fi
done
