#!/bin/bash

#PASS=$(cat .pw)
PASS=$(cat .stpw)

LOGFILE="/opt/r1soft/r1ctl/config/spooler.state"

for host in housbm03.stage.r1soft.com lobsbm01.stage.r1soft.com housbm01.stage.r1soft.com housbm02.stage.r1soft.com housbm04.stage.r1soft.com loasbm01.stage.r1soft.com; do
	data=$(sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S grep -Eo '"migration[^]]*]"' $LOGFILE" 2>/dev/null)
	if [[ ! -z $data ]]; then
 		echo "$host $data"
	fi
done
