#!/bin/bash

PASS=$(cat .pw)
LOGFILE="/opt/r1soft/r1ctl/config/spooler.state"

for host in $(awk '/csbm/ {print $2}' /etc/hosts); do
	data=$(sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S grep -Eo '"migration[^]]*]"' $LOGFILE" 2>/dev/null)
	if [[ ! -z $data ]]; then
 		echo "$host $data"
	fi
done
