#!/bin/bash

PASS=$(cat .pw)

for host in $(awk '/sbm/ {print $2}' /etc/hosts); do  
	data=$(sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S grep VMDiskFolder /opt/r1soft/r1ctl/config/dr.conf" 2>/dev/null) 
	echo "$host -> $data" 
done
