#!/bin/bash

PASS=$1

for host in 10.230.6.14 10.230.6.12 10.230.6.23 10.230.6.21 10.230.216.50; do
	data=$(sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S grep VMDiskFolder /opt/r1soft/r1ctl/config/dr.conf" 2>/dev/null) 
	echo "$host -> $data"
done
