#!/bin/bash

PASS=$(cat .pw)

for host in $(awk '/sbm/ {print $2}' /etc/hosts); do  
	data=$(sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S wc -l /usr/sbin/r1soft/conf/server.conf" 2>/dev/null) 
	echo "$host -> $data" 
done
