#!/bin/bash

PASS=$(cat .pw)

for host in $(awk '/sbm/ {print $2}' /etc/hosts); do
	#echo "**********  $host  **********"
	data=$(sshpass -p$PASS ssh -o StrictHostKeyChecking=no continuum@$host "echo $PASS | sudo -S storcli /c0/eall/sall show all | grep 'Media Error Count' | grep -v 'Count = 0'" 2>/dev/null) 
	echo "***** $host ***** -> $data"
done

