#!/usr/bin/env python

import sys
import time
import urllib2

#"wget -qO- http://10.80.65.31:57988/r1rmGA/register/csbm\?includeFTP=true"

def getCsbmList():
    response = urllib2.urlopen("http://10.80.65.31:57988/r1rmGA/register/csbm?includeFTP=true")
    content = response.read()
    return content

def main():
    csbms = []
    csbms.append(getCsbmList())
    print csbms

    
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit()

