#!/usr/bin/env python

import sys
import urllib2

#"wget -qO- http://10.80.65.31:57988/r1rmGA/register/csbm\?includeFTP=true"
#"wget -qO- http://10.80.65.31:57988/r1rmGA/csbm/<GUID>/liveConfig"

def getCsbmList():
    response = urllib2.urlopen("http://10.80.65.31:57988/r1rmGA/register/csbm?includeFTP=true")
    content = response.read()
    print content

def main():
    getCsbmList()
    
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit()





