#!/usr/bin/env python

import numpy as np
import sys
import time
import urllib2

#"wget -qO- http://10.80.65.31:57988/r1rmGA/register/csbm\?includeFTP=true"

def getCsbmList():
    response = urllib2.urlopen("http://10.80.65.31:57988/r1rmGA/register/csbm?includeFTP=false")
    content = response.read()
    return content

def main():
    csbms = []
    csbms.append(getCsbmList())
    systems = np.asarray(csbms)
    for i in systems:
        print i
        print "\n"

    
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit()

