#!/usr/bin/env python

import sys
import urllib2

#"wget -qO- http://10.80.65.31:57988/r1rmGA/csbm/<GUID>/liveConfig"

def getLiveConfig(csbm):
    url = "http://10.80.65.31:57988/r1rmGA/csbm/"+csbm+"/liveConfig"
    response = urllib2.urlopen(url)
    content = response.read()
    return content


def main():
    csbm = 'f8981d09-bb9a-4dad-8947-75ea5bd3a4dc'
    lcData = getLiveConfig(csbm)
    print lcData
    

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit()
